name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [ready_for_review]
  workflow_dispatch:

jobs:
  CI:
    uses: stetind/stem-reusable-workflows/.github/workflows/ci.yaml@main
    secrets:
      COMPOSER_ACCESS_TOKEN: ${{ secrets.COMPOSER_ACCESS_TOKEN }}

